Repository RSS3-Network/Global-Indexer, pull requests merged in 2024-06, with the labels that each got.

#266 fix(hub): invalid pending query parameter
  internal/database/dialer/cockroachdb/client_stake.go
Labels: bug

#268 fix: sorted set members
  internal/service/hub/handler/dsl/activity.go
  internal/service/hub/handler/dsl/enforcer/score_maintainer.go
Labels: bug, enhancement

#270 docs: change metadata name to camel case
  docs/openapi.go
  docs/openapi.json
  go.mod
Labels: enhancement

#272 docs: embed and array struct
  docs/openapi.go
  docs/openapi.json
  docs/openapi_test.go
Labels: enhancement

#277 docs: remove unnecessary comma
  docs/openapi.json
Labels: Documentation

#278 docs: properties required
  docs/openapi.go
  docs/openapi.json
Labels: Documentation

#279 docs: social proxy field
  docs/openapi.go
  docs/openapi.json
  docs/openapi_test.go
Labels: Documentation
