Repository RSS3-Network/Global-Indexer, pull requests merged in 2024-07, with the labels that each got.

#290 fix(settler): resolve the infinite loop logic
  internal/service/settler/settler.go
Labels: bug

#292 feat: add apis to retrieve activities
  common/httputil/http.go
  common/httputil/http_test.go
  docs/openapi.json
  internal/service/hub/handler/dsl/activity.go
  internal/service/hub/handler/dsl/distributor/distributor.go
  internal/service/hub/handler/dsl/enforcer/handle_response.go
  internal/service/hub/handler/dsl/enforcer/maintain_epoch_data.go
  internal/service/hub/handler/dsl/enforcer/maintain_epoch_data_test.go
  internal/service/hub/handler/dsl/model/model.go
  internal/service/hub/handler/dsl/router/router.go
  internal/service/hub/handler/dsl/router/router_test.go
  internal/service/hub/handler/nta/network.go
  internal/service/hub/handler/nta/node_register.go
  internal/service/hub/model/dsl/decentralized.go
  internal/service/hub/server.go
Labels: DSL

#283 fix(enforcer): enforcer data race
  internal/cache/client.go
  internal/service/hub/handler/dsl/enforcer/enforcer.go
  internal/service/hub/handler/dsl/enforcer/handle_response.go
  internal/service/hub/handler/dsl/enforcer/maintain_epoch_data.go
  internal/service/hub/handler/dsl/enforcer/maintain_reliability_score.go
  internal/service/hub/handler/dsl/enforcer/retrieve_nodes.go
  internal/service/hub/handler/dsl/enforcer/score_maintainer.go
  internal/service/hub/handler/dsl/enforcer/score_maintainer_test.go
  internal/service/hub/handler/dsl/model/model.go
  internal/service/scheduler/enforcer/reliability_score/reliability_score.go
Labels: bug, enhancement

#301 fix: possible nil tx caused panic of indexer
  internal/service/indexer/l1/indexer.go
  internal/service/indexer/l2/indexer.go
Labels: bug

#299 fix: validate combined parameters
  internal/service/hub/handler/dsl/activity.go
  internal/service/hub/handler/dsl/distributor/distributor.go
  internal/service/hub/handler/dsl/distributor/match.go
  internal/service/hub/handler/dsl/distributor/qualified_node.go
  internal/service/hub/handler/dsl/enforcer/maintain_epoch_data.go
  internal/service/hub/handler/dsl/enforcer/maintain_epoch_data_test.go
  internal/service/hub/handler/dsl/model/model.go
Labels: enhancement

#300 feat: add name service cache
  docs/openapi.json
  internal/cache/client.go
  internal/service/hub/handler/dsl/activity.go
  internal/service/hub/handler/dsl/enforcer/maintain_epoch_data.go
  internal/service/hub/handler/dsl/enforcer/maintain_reliability_score.go
  internal/service/hub/handler/dsl/enforcer/score_maintainer.go
  internal/service/hub/handler/nta/node_hide_tax_rate.go
  internal/service/hub/model/dsl/decentralized.go
  internal/service/scheduler/snapshot/apy/apy.go
Labels: enhancement

#305 fix: adjust the type of the body parameter
  common/httputil/http.go
  internal/service/hub/handler/dsl/distributor/distributor.go
  internal/service/hub/handler/dsl/model/model.go
  internal/service/hub/handler/dsl/router/router.go
Labels: bug

#303 fix: same activities with different action order
  internal/service/hub/handler/dsl/enforcer/handle_response.go
  internal/service/hub/handler/dsl/enforcer/handle_response_test.go
  internal/service/hub/handler/dsl/enforcer/maintain_reliability_score.go
  internal/service/hub/handler/dsl/enforcer/score_maintainer.go
Labels: bug

#307 fix: encode query params
  go.mod
  go.sum
  internal/service/hub/handler/dsl/activity.go
  internal/service/hub/handler/dsl/distributor/distributor.go
  internal/service/hub/handler/dsl/router/router.go
Labels: bug

#308 fix(settler): use finalized block
  internal/service/settler/server.go
Labels: bug, enhancement, Settler

#315 fix: exclude manually cancel error
  common/httputil/http.go
  internal/service/hub/handler/dsl/router/router.go
Labels: bug, enhancement

#314 fix: dsl type check
  internal/service/hub/handler/dsl/activity.go
Labels: bug

#316 fix: unique key for activity
  internal/service/hub/handler/dsl/enforcer/handle_response.go
  internal/service/hub/handler/dsl/enforcer/handle_response_test.go
Labels: bug

#319 fix(fresher): use finalized block
  internal/service/scheduler/enforcer/epoch_fresher/epoch_fresher.go
Labels: enhancement
